src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java, src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java, src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java, src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java, src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java, src/main/java/com/echall/platform/bookmark/service/BookmarkService.java, src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java, src/main/java/com/echall/platform/content/controller/ContentPublicController.java, src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java, src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java, src/main/java/com/echall/platform/content/domain/enums/ContentStatus.java, src/main/java/com/echall/platform/content/domain/enums/SearchCondition.java, src/main/java/com/echall/platform/content/repository/ContentRepository.java, src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java, src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java, src/main/java/com/echall/platform/content/service/ContentService.java, src/main/java/com/echall/platform/content/service/ContentServiceImpl.java, src/main/java/com/echall/platform/message/error/code/BookmarkErrorCode.java, src/main/java/com/echall/platform/message/error/code/ContentErrorCode.java, src/main/java/com/echall/platform/message/response/BookmarkResponseCode.java, src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java, src/main/java/com/echall/platform/message/status/ContentServiceStatus.java, src/main/java/com/echall/platform/user/domain/entity/UserEntity.java, src/main/java/com/echall/platform/user/repository/UserRepository.java
1. [[REFACTOR] 북마크 리팩토링 및 일부 기능 추가](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/104/commits/e6f9ddfd253c611cc614d7b2152bc9f29645a43b)
- 북마크 request, response 리팩토링
- 북마크 엔티티에 description 추가
- put 요청으로 description 변경 가능
- 북마크 post, put 분리
2. [[FEAT] 컨텐츠 POST, PUT 분리 및 조회 수 기능 추가](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/104/commits/621694b14939a893b5a005753465ba6d7de8851b)
- **POST, PUT 분리 아님, 일부 리팩토링 및 기능 추가 임** 
- 컨텐츠 미리보기 id 리턴 하도록 추가
- content 엔티티에 hit 컬럼 추가 (0으로 초기값)
- 게시글 상세 조회 작동 시 hit 업데이트
- sortBy, num 은 초기값을 hits, 8로 주었지만 다른 값으로 요청 가능
- 다만 아직 sortBy 조건이 여러 개인 경우는 고려하지 않음
- queryDsl 활용해서 존재하는 컬럼인지 확인
- 예외 처리 [[FEAT] 컨텐츠 미리보기 조회 시 정렬 조건 에러 추가](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/104/commits/19f7a99261b0f8f7ffa82e2019170e1d6e1 …
=> [REFACTOR] 북마크 리팩토링 및 일부 기능 추가

src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java, src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java, src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java, src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java, src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java, src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryCustom.java, src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java, src/main/java/com/echall/platform/bookmark/service/BookmarkService.java, src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java, src/main/java/com/echall/platform/content/repository/ContentRepository.java, src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java, src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java, src/main/java/com/echall/platform/message/error/code/BookmarkErrorCode.java, src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java, src/main/java/com/echall/platform/user/repository/UserRepository.java
- 북마크 전체 조회 기능 추가
- [[REFACTORING] 북마크 전체 조회 기능 수정](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/159/commits/10fc83df761fae7f464c2ff45d781429d6e1633e)
- 북마크 전체 조회 시 북마크한 컨텐츠 제목, 북마크 내용, 시간 등의 리턴 값 요청사항 반영
- 북마크 조회 시 mysql, mongo 두 db 를 모두 조회하는 것이 부담되어서 북마크 생성 시에 북마크 한 내용도 저장하는 방향으로 수정함 
- 사이즈는 255로 제한
- 수정되지 않았던 Map 리턴이나 OAuth2UserPrincipal 수정
- 북마크 생성 시 word 가 null 인 경우를 예외 처리 하여 문장 북마크 생성을 막던 것 수정
- 관련 이슈 번호: #157 
=> [FEAT] 북마크 전체 조회 기능 추가

src/main/java/com/echall/platform/config/SecurityConfig.java, src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java, src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java, src/main/java/com/echall/platform/util/CookieUtil.java
- 기존에 있었지만 사용안하던 OAuth2AuthorizationRequestBasedOnCookieRepository 사용
- 추가로 프론트에서 보낸 returnUrl을 받아 쿠키에 저장하여 OAuth2SuccessHandler에서 사용하는 방식으로 구현
- 관련 이슈 번호: #215 
- 원래 이인제 디렉터님 말씀처럼 URL로만 returnUrl을 들고 있다가 OAuth2SuccessHandler에서 가져오는 방식을 하려고 했지만, 그렇게 구현하기엔 시간이 많이 소요될 수도 있고, 가능하다고 100% 확신할 수가 없어서 쿠키 방식을 사용했습니다. (디렉터님 말씀을 제가 잘못 이해한 거일 수도 있지만요.)
- OAuth2AuthorizationRequestBasedOnCookieRepository 와 OAuth2SuccessHandler 에 쿠키를 받아오는 메서드가 있는데, 이것을 CookieUtil에 둘지 말지 의견을 주시면 감사하겠습니다.
=> [REFACTOR] OAUTH2 로그인 리다이렉트 URL 동적으로 추가하는 로직 개발

src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java, src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryCustom.java, src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java, src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
- 북마크를 생성할 때, 모든 유저에 대해 해당 북마크가 존재하는지에 대한 쿼리를 날리고 있는 것을 생성하려는 유저의 북마크에 해당 북마크가 존재하는지에 대한 쿼리를 날리도록 수정
- 수정된 쿼리
- 관련 이슈 번호: #234 
- 레포지토리 메서드에서 더 좋은 네이밍이 있으시면 추천 받습니다 ㅎㅎ..
=> [BUGFIX] 남이 생성한 북마크에 영향 받지 않도록 수정

src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java, src/main/java/com/echall/platform/util/CookieUtil.java
- OAuth2 소셜 로그인할 때 필요한 쿠키 유효시간 10초에서 3분으로 확장
- 그 외에 자잘한 코드 수정(로직은 동일)
- 관련 이슈 번호: #235 
- OAuth2 소셜 로그인할 때 인증에 사용하는 쿠키 유효시간이 10초라서 인증과정이 길어지면 쿠키가 사라져 정상적인 로그인에 실패하는 상황이 발생하여 쿠키 유효시간을 늘렸습니다.
=> [BUGFIX] OAuth2 인증 과정에서 필요한 쿠키 유효 시간 10초에서 3분으로 확장

user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCommand.java, user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkEntity.java, user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkInfo.java, user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepositoryImpl.java, user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java, user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkRequestDto.java, user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkResponseDto.java
- wordIndex 필요 없다는 프론트 요청에 따라 삭제
- 관련 이슈 번호: #264 
- 이 PR이 머지되면 아래 두 명령어로 각 DB 에서 단어 북마크 삭제 예정
- `DELETE FROM echall_local_db WHERE wordIndex IS NOT NULL;`
- `ALTER TABLE echall_local_db DROP COLUMN wordIndex ;`
=> [REFACTOR] 프론트 요청 : wordIndex 삭제

user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java, user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java, user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java, user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocument.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepositoryCustom.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepositoryImpl.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java, user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentRequestDto.java, user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java, user-api/src/main/java/com/biengual/userapi/message/response/ContentResponseCode.java
- content api 관련 querydsl을 JPAQueryFactory를 활용한 ContentCustomRepository로 수정
- content api의 modify 삭제
- content api의 deactivate 를 toggle-active 로 수정하고 요청마다 ACTIVATED <-> DEACTIVATED 할 수 있도록 수정
- 리턴 상태 메세지 수정
- 관련 이슈 번호: #282
=> [REFACTOR] content-api querydsl 수정 및 일부 api 수정

user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java, user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java, user-api/src/main/java/com/biengual/userapi/content/domain/UserContentBookmarks.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
- dto와 info 멤버변수에 bookmarkId 추가
- 추가적으로 본인의 북마크가 삭제된 것이 아니면 예외를 던지도록 구현
- 관련 이슈 번호: #320
=> [BUGFIX] 컨텐츠 디테일 조회시 bookmarkId도 추가로 보내도록 수정

biengual-core/src/main/java/com/biengual/core/util/CookieUtil.java
- 30초가 아니라 3분에서 -> 5 분으로 변경
- 관련 이슈 번호: #338
=> [REFACTOR] oauth2 인증 유효시간 3 -> 5분으로 변경

user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
- 프론트 요청 : content 조회 API 중  preview, search, scrap-count 에 isPointRequired 리턴 값 추가
- 관련 이슈 번호: #310
=> [FEAT] 컨텐츠 preview, search, scrap-count 에 isPointRequired 추가

biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java, biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java, user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java, user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java, user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java, user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java, user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java, user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java, user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetCurrentPointDto.java, user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetCurrentPoint.java, user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
- Layered Architecture 컨벤션에 맞게 구현
- 관련 이슈 번호: #369 
- 유저 포인트를 가져오는 UserReader가 있긴 한데, DashboardReader 를 만들고 같은 UserCustomRepository의 findUserPointByUserId 메서드를 사용했습니다. 이에 다른 의견 있으시면 말씀해주세요.
=> [FEAT] 대시보드 - 유저 현재 포인트 조회 기능 개발

user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java, user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java, user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java, user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
- Dto, Info 구조 변경
- Mapper, Reader 로직 변경
- 관련 이슈 번호: #381 
- 기존 learningRate 대신 curentLearningRate와 completedLearningRate 사용합니다.
=> [REFACTOR] 프론트 요청으로 인한 컨텐츠 디테일 조회 응답에 curentLearningRate와 completedLearningRate 추가

biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java, user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java, user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java, user-api/src/main/java/com/biengual/userapi/user/presentation/UserPublicController.java, user-api/src/main/java/com/biengual/userapi/user/presentation/UserRequestDto.java
- Dto의 NotNull 제거
- DataProvider에서 null 체크 로직 추가
- 해당 기능의 Facade  메서드 제거하고 Controller에서 해당 기능의 Service 메서드 호출
- 관련 이슈 번호: #404
=> [REFACTOR] 프론트 요청에 따라 본인 정보 수정 시 CategoryIds를 Optional하게 요청할 수 있게 수정

biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java, user-api/src/main/java/com/biengual/userapi/validator/ContentValidator.java
- ContentValidator의 verifyLearnableContent메서드에서 ContentStatus를 반대로 체크하던 것을 수정
- 관련 이슈 번호: #406
=> [BUGFIX] ContentStatus를 반대로 체크하던 것을 수정

biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java, biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java, biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentLevelFeedbackDataMart.java, biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentLevelFeedbackHistoryEntity.java, biengual-core/src/main/java/com/biengual/core/domain/entity/metadata/AggregationMetadataEntity.java, biengual-core/src/main/java/com/biengual/core/enums/IntervalType.java, biengual-core/src/main/java/com/biengual/core/response/error/code/MetadataErrorCode.java, biengual-core/src/main/java/com/biengual/core/response/error/code/ServerError.java, biengual-core/src/main/java/com/biengual/core/response/status/MetadataServiceStatus.java, biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java, biengual-core/src/main/java/com/biengual/core/util/TimeRange.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentLevelFeedbackDataMartCustomRepository.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentLevelFeedbackDataMartRepository.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentLevelFeedbackHistoryCustomRepository.java, user-api/src/main/java/com/biengual/userapi/metadata/domain/AggregationMetadataRepository.java, user-api/src/main/java/com/biengual/userapi/metadata/domain/MetadataStore.java, user-api/src/main/java/com/biengual/userapi/metadata/infrastructure/MetadataStoreImpl.java, user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java, user-api/src/main/java/com/biengual/userapi/schedule/domain/ScheduleService.java, user-api/src/main/resources/db/migration/V1.14.0__alter.sql, user-api/src/main/resources/db/migration/V1.14.1__create.sql, user-api/src/main/resources/db/migration/V1.14.2__create.sql, user-api/src/main/resources/db/migration/V1.14.3__alter.sql, user-api/src/main/resources/db/migration/V1.14.4__alter.sql
- 집계 테이블의 메타데이터를 저장하기 위한 AggregationMetadata 엔티티 및 Flyway 버전 추가
- 전체 기간 동안 ContentLevelFeedback에 대한 집계를 보여주기 위한 ContentLevelFeedbackDataMart 엔티티 및 Flyway 버전 추가
- 집계 기능에 맞게 ContentLevelFeedbackHistory 엔티티 수정 및 Flyway 버전 추가
- 집계 기능을 위한 Scheduler, DataProvider, Repository, Info, Util 구현
- Scheduler는 오전 4시에 동작하게 구현
- 관련 이슈 번호: #393 
- 집계 로직이 커서 이후 PR에 Content에 집계 결과에 대한 ContentLevel를 반영하고, 컨텐츠 관련 응답 Dto에 ContentLevel을 추가할 예정입니다.
- 집계 로직은 개선 후 성능을 비교해보고자 for문으로 순차 처리하도록 구현했습니다.
=> [FEAT] 컨텐츠 난이도 피드백 내역 집계 기능 개발

biengual-core/src/main/java/com/biengual/core/annotation/RedisDistributedLock.java, biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java, biengual-core/src/main/java/com/biengual/core/response/error/code/PointErrorCode.java, biengual-core/src/main/java/com/biengual/core/response/status/MetadataServiceStatus.java, biengual-core/src/main/java/com/biengual/core/response/status/PointServiceStatus.java, biengual-core/src/main/java/com/biengual/core/response/success/PointSuccessCode.java, user-api/src/main/java/com/biengual/userapi/aop/RedissonLockAspect.java, user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java, user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java, user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java, user-api/src/main/java/com/biengual/userapi/point/application/PointServiceImpl.java, user-api/src/main/java/com/biengual/userapi/point/domain/PointService.java, user-api/src/main/java/com/biengual/userapi/point/presentation/PointPublicController.java, user-api/src/main/java/com/biengual/userapi/validator/ContentValidator.java, user-api/src/main/java/com/biengual/userapi/validator/PointValidator.java, user-api/src/test/java/com/biengual/userapi/domain/content/ContentTestFixture.java, user-api/src/test/java/com/biengual/userapi/domain/point/PointConcurrencyTest.java
- 최신 컨텐츠에 대한 포인트 차감을 API로 분리
- Layered Architecture 컨벤션에 따라 해당 API를 구현
- 최신 컨텐츠에 대한 포인트 차감 서비스 로직 동시성 테스트 구현
- 동시성 문제를 확인함에 따라 Redis 분산 락 적용
- 관련 이슈 번호: #451
=> [REFACTOR] 컨텐츠 상세 조회와 최신 컨텐츠 포인트 차감 로직 분리

user-api/src/main/java/com/biengual/userapi/question/domain/QuestionDocumentRepository.java, user-api/src/main/java/com/biengual/userapi/question/domain/QuestionInfo.java, user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java, user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionDtoMapper.java
- Projection 대상 클래스인 QuestionInfo.Detail의 멤버 변수 questionId를 id로 변경함으로써 매핑이 되도록 수정
- QuestionInfo.Detail의 변경됨에 따라 관련 로직 수정
- 관련 이슈 번호: #457 
- Question Document 의 id는 Projection 대상 클래스인 QuestionInfo.Detail의 멤버 변수에 동일한 이름인 id가 존재하지 않기 때문에 매핑이 되지 않아서 QuestionInfo.Detail의 questionId가 null이 되어서 발생한 버그입니다.
- QueryDsl 없이 Spring Data MongoDB만 의존성을 추가했을 경우 Projection 하는 방법은 3가지가 있었습니다.
- 1. 지금처럼 Projection 대상 클래스의 멤버 변수를 Document 필드 이름과 동일하게 구성
- 2. Spring Data MongoDB 기능인 Projection Interface 생성
- 3. MongoDB Converter 구현
- 저는 MapStruct를 사용하고 있고, 현재 Info 구조에 1. 이 가장 낫다고 판단하여 1. 으로 해결했습니다.
=> [BUGFIX] Question 조회 시 QuestionId 가 null로 오는 버그 해결

user-api/src/main/java/com/biengual/userapi/config/OpenSearchConfig.java, user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
-[HOTFIX] OpenSearch DEV 연결 테스트
=> [HOTFIX] OpenSearch DEV 연결 테스트

biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java, user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderReaderImpl.java, user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
- LocalDateTime.from 을 사용하는 것이 아닌 LocalDate.atStartOfDay 를 사용하는 것으로 변경
- 관련 이슈 번호: #466 
- LocalDateTime.from 메서드는 입력으로 LocalDate 타입을 받을 수 없어서 발생한 버그입니다.
- createBookmarkRecommender 기능도 잘 동작합니다.
=> [BUGFIX] 북마크 추천 기능 서버 에러 해결

biengual-core/src/main/java/com/biengual/core/util/StringListConverter.java, user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java, user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningReaderImpl.java, user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
- category_recommender에서 similar_category_ids가 "" 인 경우에 대한 convert 처리 추가
- 추천할 카테고리가 하나도 없는 경우에 대한 로직 추가
- 관련 이슈 번호: #469 
- category_recommender에서 similar_category_ids가 "" 인 경우에 QueryDsl에서 가져올 때 ""로 가져와서 `For input string: ""` 에러가 발생합니다.
- 위의 버그와 관련해서 where 문에서 categoryRecommenderEntity.similarCategoryIds 가 빈리스트가 아닌경우로 해결하려 했으나, 제가 판단하기론 QueryDsl은 ""을 빈리스트로 인식했지만, 하버네이트는 ""으로 인식해서 매핑이 안되는 문제가 발생합니다.
- 추천할 카테고리가 하나도 없는 경우에 index 관련 에러가 발생합니다.
=> [BUGFIX] 카테고리 기반 컨텐츠 추천 기능 에러 해결

user-api/src/main/java/com/biengual/userapi/image/infrastructure/ImageReaderImpl.java
- getImage method 의 URI 리턴에서 "https://" 삭제
=> [HOTFIX] getImage method 의 URI 리턴에서 "https://" 삭제

user-api/src/main/java/com/biengual/userapi/config/HttpRequestFilterConfig.java, user-api/src/main/java/com/biengual/userapi/filter/ServerTimingFilter.java
- OncePerRequestFilter 를 extends 한 ServerTimingFilter 구현
- 기존 HttpRequestFilterConfig에서 필터 등록
- 해당 필터는 local과 dev에서 작동하도록 설정
- 관련 이슈 번호: #488 
- ContentCachingResponseWrapper를 사용한 이유는 response가 commit 되기 전에만 수정이 가능하기 때문에 commit 되는 시점을 늦추기 위해서 사용했습니다.
=> [FEAT] 프론트 요청으로 인한 Server Timing API를 위한 Filter 추가

user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingReaderImpl.java
- rss 에서 유튜브 컨텐츠 업데이트 url 받을 시 예외 처리 추가
- 기존 로직에서 예외를 catch 하지 않아서 유튜브 rss 에서 업데이트할 컨텐츠가 없으면 크롤링 작업 자체가 멈추게 되어 있어서 이를 catch 하는 로직 추가함
=> [HOTFIX] rss 에서 유튜브 컨텐츠 업데이트 url 받을 시 예외 처리 추가
