Kernel360/F2-BIENGUAL-BE

- .gitignore
- build.gradle
- docker-compose.yml
- settings.gradle
- src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
- src/main/java/com/echall/platform/config/SwaggerConfig.java
- src/main/resources/application.yml
- src/main/resources/yml/application-dev.yml
- src/main/resources/yml/application-local.yml
- src/main/resources/yml/application-prod.yml
- src/main/resources/yml/logging/application-log.yml
- src/test/java/com/echall/platform/EnglishChallengePlatformApplicationTests.java
#2 
- DB Local Docker setting
- MySQL
- Redis
- Mongo
- Swagger Config setting
- [주소](http://localhost:8080/api-info)
- #2에서 완료되지 않은 부분은 Pair Progamming 후에 추가될 예정
> [FEAT] : Default Setting

- build.gradle
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- src/main/java/com/echall/platform/user/controller/UserPublicController.java
- src/main/java/com/echall/platform/user/domain/dto/UserRequestDto.java
- src/main/java/com/echall/platform/user/domain/dto/UserResponseDto.java
- src/main/java/com/echall/platform/user/domain/entity/BaseEntity.java
- src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
- src/main/java/com/echall/platform/user/domain/enums/Gender.java
- src/main/java/com/echall/platform/user/domain/enums/Role.java
- src/main/java/com/echall/platform/user/domain/enums/UserStatus.java
- src/main/java/com/echall/platform/user/repository/UserRepository.java
- src/main/java/com/echall/platform/user/repository/custom/UserRepositoryCustom.java
- src/main/java/com/echall/platform/user/repository/custom/UserRepositoryImpl.java
- src/main/java/com/echall/platform/user/service/UserService.java
- 페어 프로그래밍을 통해 코드 컨벤션을 맞추는 작업 진행
- #5 에 필요한 user 작업
- Social Login 은 추후 진행 예정이므로 로그인 관련 부분은 `String email`을 임의의 값으로 세팅
> [FEAT]: Pair Programming for Code Convention

- build.gradle
- src/main/generated/com/echall/platform/user/domain/entity/QBaseEntity.java
- src/main/generated/com/echall/platform/user/domain/entity/QUserEntity.java
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- src/main/java/com/echall/platform/user/domain/dto/UserRequestDto.java
- src/main/java/com/echall/platform/user/domain/dto/UserResponseDto.java
- src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
- src/main/java/com/echall/platform/user/domain/enums/UserStatus.java
- src/main/java/com/echall/platform/user/repository/UserRepository.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/resources/application.yml
- src/main/resources/templates/naver-intellij-formatter.xml
- src/main/resources/yml/application-local.yml
#5 
- 기본적인 user 관련 CRUD
- Spring Security 추가 필요함 
- Test Code 이어서 추가 예정
- Security 연결 끝나면 Swagger 수정 예정
- content 추가되면 유저의 챌린지 조회 관련 내용 추가 예정
> [FEAT] : User CRUD Initial version

- src/main/java/com/echall/platform/exception/challenge/ApiChallengeErrorSubCategory.java
- src/main/java/com/echall/platform/exception/challenge/ApiChallengeException.java
- src/main/java/com/echall/platform/exception/common/ApiErrorCategory.java
- src/main/java/com/echall/platform/exception/common/ApiErrorResponse.java
- src/main/java/com/echall/platform/exception/common/ApiErrorSubCategory.java
- src/main/java/com/echall/platform/exception/common/ApiException.java
- src/main/java/com/echall/platform/exception/common/ApiExceptionHandler.java
- src/main/java/com/echall/platform/exception/content/ApiContentErrorSubCategory.java
- src/main/java/com/echall/platform/exception/content/ApiContentException.java
- src/main/java/com/echall/platform/exception/review/ApiReviewErrorSubCategory.java
- src/main/java/com/echall/platform/exception/review/ApiReviewException.java
- src/main/java/com/echall/platform/exception/user/ApiUserErrorSubCategory.java
- src/main/java/com/echall/platform/exception/user/ApiUserException.java
#12 
- Http 관련 CustomException 추가
- User 관련 CustomException 추가
- Challenge 관련 CustomException 추가
- Content 관련 CustomException 추가
- Review 관련 CustomException 추가
> [FEAT] : 기본적인 customException 생성

- .gitignore
- build.gradle
- src/main/generated/com/echall/platform/category/domain/entity/QCategoryEntity.java
- src/main/java/com/echall/platform/config/P6SpySqlFormatter.java
- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/oauth2/domain/GoogleUserInfo.java
- src/main/java/com/echall/platform/oauth2/domain/KakaoUserInfo.java
- src/main/java/com/echall/platform/oauth2/domain/NaverUserInfo.java
- src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
- src/main/java/com/echall/platform/user/controller/UserPublicController.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/resources/templates/login.html
feat/#2/kakao-naver-login -> dev (예: `feature/login` -> `develop`)
- Social login 에 kakao, naver 추가
- 관련 이슈 번호: #2 
- **노션에 바뀐 env 파일 적용 필수 입니다**
> [FEAT] : Social Login - Add Platforms

- src/main/java/com/echall/platform/user/service/UserService.java
- src/test/java/com/echall/platform/user/controller/UserApiControllerTest.java
- src/test/java/com/echall/platform/user/service/UserServiceTest.java
Feature 브랜치명 -> 대상 브랜치명 (예: `feature/#25/userServiceTest` -> `develop`)
- UserService 의 AssertThat_UserAccountIsAppropriate 함수 private => protected
- none
- 관련 이슈 번호: #25 
- Controller 관련 테스트코드 추가 필요
- [ x ] 코드가 정상적으로 동작하는지 확인
- [ x ] 새로운 테스트를 추가했거나 기존 테스트를 통과하는지 확인
- [ x ] 코드 스타일 가이드에 맞게 포맷팅했는지 확인
> [TEST] : User Service 테스트 코드 추가

- build.gradle
- src/main/java/com/echall/platform/config/SwaggerConfig.java
- src/main/java/com/echall/platform/oauth2/controller/TokenApiController.java
- src/main/java/com/echall/platform/oauth2/domain/NaverUserInfo.java
- src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
feat/#2/refactor-oauth2 -> dev
- oauth2 naver 유저 네임 추가
- provider 메소드로 변경
- swagger 관련 jwt 적용
- 관련 이슈 번호: #2 
> [REFACTOR] : Refactor about OAuth2-Naver and Swagger

- .github/workflows/deploy.yml
- workflow 환경 세팅
- none
- 관련 이슈 번호: #28
> [FEAT] :  workflow 설정

- CalculatorQuestionDifficulty.py
- GenerateContentMatchingQuestions.py
- GenerateFIBQuestions.py
- GenerateWordQuestions.py
- PreProcess.py
- packages.py
feat/#23/generator-question -> dev
- text 로 되어 있는 부분 하나의 글로 묶고 필요 없는 부분 전처리
- PreProcess 과정은 한번 진행하면 xlsx 로 저장하고 log에 파일명 저장해서 여러번 작업하지 않게 처리
- 문제 부분도 문제 유형 확정되면 로그 처리해서 한 번만 동작해서 충분한 양의 문제를 저장하도록 할 예정
- 문제 생성
- 내용 일치 - 주관식
- 빈칸 채우기 - 객관식
- 단어 한국어 뜻 맞추기 - 객관식
- 문제 난이도 설정(아직 제대로 적용 안 됨) -> 문제 확정 나면 적용 예정
- 내용 일치
- 빈칸 채우기
- 단어 뜻맞추기 
- 관련 이슈 번호: #23 
@godhyzzang
> [FEAT]: PreProcess and Genrator Questions

- GenerateFIBQuestions.py
- GenerateWordQuestions.py
feat/#23/generator-question -> dev
- 좀 더 자연스러운 문제가 되도록 필터 추가
> [REFACTOR] : refactor for generating more accurate problems

- appspec.yml
- scripts/start.sh
- scripts/stop.sh
Feature 브랜치명 -> 대상 브랜치명 (`docs/#28/init-shell` -> `dev`)
- 자동 배포시 실행할 스크립트 작성
- 관련 이슈 번호: #28 
- 차후 서버에 Python 코드 관련 권한 설정 필요
- 상시 테스트 필요
> [DOCS] : 배포 시 실행 할 스크립트 작성

- .github/workflows/deploy.yml
에러 해결중
Feature 브랜치명 -> 대상 브랜치명 (예: `xorwns118-patch-2` -> `dev`)
> [FIX] : deploy.yml

- .github/workflows/deploy.yml
Feature 브랜치명 -> 대상 브랜치명 (예: `xorwns118-patch-3` -> `dev`)
- 관련 이슈 번호: #28 
> [BUGFIX] : deploy.yml 테스트코드 무시 명령어 추가

- Dockerfile
`fix/#28/cicdSetting-1` -> `dev`
- ci/cd 에 필요한 도커파일 생성
- x
- 관련 이슈 번호: #28 
- `fix/#28/cicdSetting` -> `dev` PR commit 내용 참고
> Workflow를 위한 Dockerfile 생성

- src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
- src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
- src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
- src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
- src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
- src/main/java/com/echall/platform/bookmark/service/BookmarkService.java
- src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/echall/platform/content/controller/ContentPublicController.java
- src/main/java/com/echall/platform/content/domain/enums/SearchCondition.java
- src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
- src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
- src/main/java/com/echall/platform/content/service/ContentService.java
- src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- src/main/java/com/echall/platform/user/controller/UserPublicController.java
- src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
feat/#5/bookmark-crud -> feat
- 북마크 추가, 삭제 기능 추가
- SearchCondition 위치 변경
- 관련 이슈 번호: #5 
> [FEAT] Bookmark 기능 추가

- src/main/java/com/echall/platform/category/controller/CategoryApiController.java
- src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/config/SwaggerConfig.java
- src/main/java/com/echall/platform/config/TokenAuthenticationFilter.java
- src/main/java/com/echall/platform/content/controller/ContentPublicController.java
- src/main/java/com/echall/platform/oauth2/TokenProvider.java
- src/main/java/com/echall/platform/user/controller/UserPublicController.java
- src/main/java/com/echall/platform/user/domain/enums/Role.java
feat/#45/swagger-security -> dev
- Swagger Config 에 JWT 관련 설정 추가
- swager를 이용한 접근 권한 확인은 로컬 환경에서 테스트 해야 함
- Security Config 에 path 에 따른 접근 권한 설정
- ROLE_DEVELOPER는 swagger 를 위한 계정 권한으로 모든 path에 접근 가능
- 이와 관련해서 배포 시 Security Config 에 주석으로 처리 된 부분 주석 해제 필요 @xorwns118 
- 관련 이슈 번호: #45 
> [FEAT] SwaggerConfig and SecurityConfig 관련 권한 설정

- src/main/java/com/echall/platform/config/SecurityConfig.java
`bugfix/#45/fixUrl` -> `dev`
- url 수정
- x
- 관련 이슈 번호: #45
> [HOTFIX] : SecurityConfig 파일 수정

- build.gradle
- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/config/YoutubeAppConfig.java
- src/main/java/com/echall/platform/content/controller/ContentApiController.java
- src/main/java/com/echall/platform/crawling/controller/CrawlingController.java
- src/main/java/com/echall/platform/crawling/domain/dto/CrawlingRequestDto.java
- src/main/java/com/echall/platform/crawling/domain/dto/CrawlingResponseDto.java
- src/main/java/com/echall/platform/crawling/service/CrawlingService.java
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- src/main/resources/application.yml
feat/#45/crawler -> dev
**_현재 코드는 Swagger 테스트용, 어느 정도 크롤러의 안정성이 보장되면 컨텐트 쪽으로 합쳐질 예정_**
- 유튜브 API 를 이용하여 url, 채널 이름, 제목, 이미지 url, 카테고리 받아옴
- Selenium을 사용해서 스크립트(영문)을 저장함
- 영상 길이에 따른 데이터 크롤링 거부 로직 추가 예정
- [[REFACTORING] YouTube 크롤러 리팩토링](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/53/commits/ae11295e92ae88de4a9661f200fd9559d658db65)
- 드라이버를 영어로 세팅해서 무조건 영어 스크립트를 받아 올 수 있게 변경
- 유튜브 영상 길이가 10분 초과이면 예외 발생 -> 10분까지만 크롤링 가능
- 추후 비동기로 처리할 예정
- [[FEAT] CNN 크롤링](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/53/commits/ae22a9d14c521698cf1a34052b067cbe17510fcc)
- Jsoup을 이용한 크롤링
- CNN Articles까지 작업 끝나고 DB 저장 관련 커밋 새로운 branch로 리팩토링 예정
- createContent 로 합쳐질 예정
- 아직 테스트가 더 필요 함
- 관련 이슈 번호: #45
> [FEAT] YouTube Crawler by using API & Selenium

- src/main/java/com/echall/platform/config/WebConfig.java
> [REFACTOR] WebConfig 추가

- src/main/java/com/echall/platform/user/controller/UserApiController.java
> [REFACTOR]usercontroller

- src/main/java/com/echall/platform/util/CookieUtil.java
> [REFACTOR] cookieutil

- src/main/java/com/echall/platform/config/SecurityConfig.java
> [REFACTOR] SecurityConfig

- src/main/java/com/echall/platform/config/WebConfig.java
> [REFACTOR] WebConfig

- src/main/java/com/echall/platform/config/SecurityConfig.java
> [REFACTOR] Security Cors

- .github/workflows/deploy.yml
- Dockerfile
setting/#73/dev-cd -> dev
- Dockerfile에서 SPRING_PROFILES_ACTIVE를 제거한 이유는 지금은 서버가 하나라 굳이 사용하지 않았음(만약 서버가 추가되면 docker-compose를 이용할 예정)
- depoly.yml은 merge되면 빌드하고 도커허브에 올리는 if-dev-merge job과 EC2 서버에 배포하는 deploy jop으로 나누었습니다.
- 관련 이슈 번호: #73 
> [SETTING] deploy.yml, Dockerfile 변경

- src/main/resources/yml/application-local.yml
- src/main/resources/yml/application-prod.yml
> [HOTFIX] application-local.yml, application-prod.yml 구글 리다이렉트 uri 삭제

- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/config/WebConfig.java
- src/main/java/com/echall/platform/oauth2/OAuth2FailureHandler.java
- src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- src/main/resources/yml/application-local.yml
- src/main/resources/yml/application-prod.yml
- 쿠키 domain, httpOnly 설정 변경
- 소셜로그인 실패 시 로그 로직 추가
- Cors 설정 WebMvcConfigurer에서 하도록 변경
- 관련 이슈 번호: #76 
- nginx 설정은 아직 미변경(이 PR 머지된 후 동작을 보면서 수정해야 한다면 수정할 예정)
> [SETTING] https 환경을 위한 쿠키 설정

- src/main/java/com/echall/platform/util/CookieUtil.java
> [FIX] 쿠키 domain 설정 변경

- src/main/java/com/echall/platform/config/WebConfig.java
- https://front.biengual.store가 추가됨에 따라 추가
> [FIX] Cors 설정 Origin 추가

- src/main/java/com/echall/platform/config/SecurityConfig.java
- 스프링 시큐리티 cors 주소에 https 로컬 주소 추가
- 관련 이슈 번호: #85 
- 시연 후 #83 이슈에 대해 논의할 것 같습니다.
> [TEST] 시연을 위한 cors 설정

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- Dockerfile
- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- src/main/resources/application.yml
- src/main/resources/yml/application-dev.yml
- application-dev.yml이 생기면서 구분이 필요한 변수 추가 및 깃허브 시크릿 키, 노션 변경 .env 적용
- dev 환경이 추가됨에 따라 쿠키 설정 로직에 반영
- dev 환경이 추가됨에 따라 스프링 시큐리티 Cors 설정 로직에 반영
- dev 환경이 추가됨에 따라 deploy 워크플로우 분리 및 Dockerfile에 반영
- EC2 Unbuntu로 Dev 서버 새로 만들었고, 탄력적 IP 적용
- EC2 Unbuntu로 Prod 서버 새로 만들었고, 탄력적 IP 적용
- Prod는 만들기만 하고 배포 진행 x
- 관련 이슈 번호: #83 
- .env에 운영 서버만 사용하는 url는 추후 추가해야함
- 이 PR이 머지가 된 후 예정 작업 플로우: 개발 서버 스프링부트가 잘 돌아가는지 확인 -> 기존 EC2 서버 삭제 -> 도메인 정리 -> https 적용 -> 프론트 로컬 환경에서 잘 돌아가는지 확인 -> 운영 서버 작업
> [SETTING] 개발 서버와 운영 서버를 위한 세팅

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- docker build 부분이 실패해서 수정
- 관련 이슈 번호: #88 
- 이 PR 워크플로우도 실패하면 이미지 이름 받는 부분을 수정할 예정
> [REFACTOR] 배포 워크플로우 dev와 prod 수정

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- docker 이미지 build, push, pull 하는 부분에서 ${{ secrets.DOCKERHUB_REPOSITORY }}를 받는 부분을 변경
- 관련 이슈 번호: #88 
- 이거도 안되면 영래님 docker hub를 확인해보거나 제걸 사용해보겠습니다.
> [REFACTOR] 배포 워크플로우 dev와 prod 수정 2차

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- docker hub 계정 변경
- docker hub에서 dev는 public 레포로 생성
> [REFACTOR] 배포 워크플로우 dev와 prod 수정 3차

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
> [REFACTOR] 배포 워크플로우 dev와 prod 수정 4차

- Dockerfile
- Dockerfile에서 jar파일 위치 수정 및 copy .env 삭제
> [BUGFIX] Dockerfile 수정

- Dockerfile
- app.jar 파일 위치에 .env가 있어야 실행이 가능함을 확인
> [BUGFIX] Dockerfile 수정 2차

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- build 할 때 PROFILES 값이 안들어가서 run 할 때 넣는 것으로 수정
> Bugfix: dev prod 워크플로우 수정 6차

- build.gradle
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
- src/main/java/com/echall/platform/crawling/service/TranslateService.java
- src/main/java/com/echall/platform/message/error/code/CrawlingErrorCode.java
- src/main/resources/application.yml
- [[REFACTOR] Microsoft Azure AI Translator 로 번역 방식 수정](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/97/commits/7def2af4e254ad86823c60f0204ac3a6c070f513) 번역 파이썬 에서 Microsoft 의 Azure AI Translator API 사용
- [[REFACTOR] CrawlingErrorCode 수정](https://github.com/Kernel360/F2-ENGLISH-CHALLENGING-BE/pull/97/commits/7a292f6fb2f42e1da63a09175f25077c637ecf0b) 에러코드인데 NO_CONTENT 204 였기 때문에 NOT_ACCEPTABLE 406 으로 수정 
- 노션 팀페이지  : 이슈해결 - 번역 관련 에 가격 비교 및 번역 결과 업로드 함
- 관련 이슈 번호: #51
- env 파일 업데이트 확인
> [REFACTOR] Microsoft Azure AI Translator 로 번역 방식 수정

- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/config/TokenAuthenticationFilter.java
- src/main/java/com/echall/platform/message/error/code/TokenErrorCode.java
- src/main/java/com/echall/platform/message/error/code/UserErrorCode.java
- src/main/java/com/echall/platform/message/error/exception/OAuth2AuthenticationProcessingException.java
- src/main/java/com/echall/platform/message/status/TokenServiceStatus.java
- src/main/java/com/echall/platform/message/status/UserServiceStatus.java
- src/main/java/com/echall/platform/oauth2/AccessDeniedHandlerImpl.java
- src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
- src/main/java/com/echall/platform/oauth2/TokenProvider.java
- src/main/java/com/echall/platform/oauth2/domain/entity/RefreshToken.java
- src/main/java/com/echall/platform/oauth2/domain/enums/OAuth2Provider.java
- src/main/java/com/echall/platform/oauth2/domain/info/GoogleUserInfo.java
- src/main/java/com/echall/platform/oauth2/domain/info/KakaoUserInfo.java
- src/main/java/com/echall/platform/oauth2/domain/info/NaverUserInfo.java
- src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserInfo.java
- src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserInfoFactory.java
- src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserPrincipal.java
- src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
- src/main/java/com/echall/platform/oauth2/service/RefreshTokenService.java
- src/main/java/com/echall/platform/oauth2/service/TokenService.java
- src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
- src/main/java/com/echall/platform/user/repository/UserRepository.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- src/main/java/com/echall/platform/util/HttpServletResponseUtil.java
- src/main/resources/application.yml
- 클래스에 대한 역할 분리(CookieUtil, TokenProvider, RefreshService)
- Provider에 따른 OAuth2User 를 만들어주도록 함
- 로그인 또는 인증 시 AssertThat_UserAccountIsAppropriate을 하도록 함
- 서비스 단에서 사용할 OAuth2UserPrincipal 구현
- 인증, 인가 예외 처리 로직 추가
- 관련 이슈 번호: #96 
- 기존에 있는 에러코드 U-R-901 를 U-T-901 변경하려고 합니다. 
- 에러코드 U-R-901를 변경하는 이유는 Token 도메인에 포함된다고 생각하기 때문입니다.
- 변경에 동의하시면 Dev 서버에 배포 후 노션에 반영하겠습니다.
- JWT로 인증을 하고 있으므로, 인증 에러 코드는 TokenErrorCode에 뒀습니다.
- 인가는 User의 Role로 확인하므로, 인가 에러코드는 UserErrorCode에 뒀습니다.
> [REFACTOR] 소셜 로그인 로직 및 인증 로직 리팩토링

- .gitignore
- src/main/java/com/echall/platform/annotation/LoginLogging.java
- src/main/java/com/echall/platform/aop/LoggingAspect.java
- src/main/java/com/echall/platform/message/status/UserServiceStatus.java
- src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
- src/main/resources/logback.xml
- OAuth 로그인, REST Controller 성공 응답, REST Controller 에러 응답에 대한 로그를 AOP로 출력
- 로그 파일로 저장하는 것은 logback.xml을 이용하여 저장
- 관련 이슈 번호: #102 
- 로그 정책에 대한 내용은 노션에 정리하겠습니다.
- ELK 대시보드를 로컬환경에서 구축 성공했고, 관련 설정들도 노션에 정리하겠습니다.
- 이 후, ELK 서버 구축을 해보겠습니다.
- 대충 남긴 로그들에 대한 정리도 필요해보입니다.
> [FEAT] 로그 모니터링 코드 구현

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- deploy.yml 에서 docker run 할 때 -v 옵션으로 logs 매핑
- 관련 이슈 번호: #106 
- 비용 이슈로 모든 로그를 Elasticserach에 저장하는 것은 아니기 때문에 매핑 진행했습니다.
> [SETTING] 도커 컨테이너 logs 매핑

- src/main/java/com/echall/platform/config/SecurityConfig.java
> [HOTFIX] cors 수정

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] selenium os 설정

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] selenium options 수정

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- src/main/resources/logback.xml
- logback에서 로그 타임존을 한국시간으로 설정
- deploy에서 filebeat 도커 컨테이너를 지우지 못하도록 수정
- 관련 이슈 번호: #116
> [SETTING] 로그 시간 타임존 설정 및 deploy 수정

- src/main/java/com/echall/platform/content/controller/ContentPublicController.java
- src/main/java/com/echall/platform/content/domain/enums/ContentType.java
- src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] 오타 수정

- Dockerfile
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] selenium options, docker file 수정

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] 확인용 log 추가

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] thread sleep 변경

- Dockerfile
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] docker file, crawling option 변경

- Dockerfile
> [HOTFIX] docker file 변경

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] Xvfb 옵션 수정

- Dockerfile
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] Xvfb 세팅 수정

- Dockerfile
> [HOTFIX] dockerfile 수정

- Dockerfile
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] dockerfile 수정 및 log 추가

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] log 추가

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] 더보기 버튼 조건 삭제

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] 더보기 버튼 조건 수정

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] ChromeOptions 수정

- Dockerfile
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] Xvfb 실행

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] xpath 및 js로 버튼 실행 하도록 수정

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] headless 삭제

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] button 클릭 방법 수정

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
- src/test/java/com/echall/platform/user/service/UserServiceTest.java
> [HOTFIX] driver log 추가

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] log 수정

- Dockerfile
- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
- src/test/java/com/echall/platform/user/service/UserServiceTest.java
> [FEAT] dev to main

- src/main/java/com/echall/platform/message/response/ScrapResponseCode.java
- src/main/java/com/echall/platform/message/status/ScrapServiceStatus.java
- src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
- src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
- src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryCustom.java
- src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
- src/main/java/com/echall/platform/scrap/service/ScrapService.java
- src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
- 스크랩 삭제 요청 contentId 로 요청 가능하게 수정
- contentId 기반으로 스크랩 확인 요청 기능 추가
- 관련 이슈 번호: #160 
> [REFACTORING] 스크랩 리팩토링 및 조회 기능 추가

- src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
- 북마크 detail col 크기 변경 255 -> 512
- 관련 이슈 번호: #162
- docker update 로 반영되지 않아 DB 에서 직접 수정
- 리뷰까지 필요 없는 내용이므로 바로 머지
> [HOTFIX] 북마크 디테일 크기 변경

- src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
- src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
- src/main/java/com/echall/platform/scrap/service/ScrapService.java
- src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
> [HOTFIX] 스크랩 Get 요청 수정

- src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
- src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
- src/main/java/com/echall/platform/scrap/domain/dto/ScrapResponseDto.java
- src/main/java/com/echall/platform/scrap/domain/entity/ScrapEntity.java
- src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
- src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
- src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
- 내 스크랩 조회 시 프론트 요청에 따른 리턴 타입 수정
- scrap, content 매핑 추가
> [HOTFIX] 스크랩 리턴 타입 수정

- src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
- src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
- src/main/java/com/echall/platform/content/controller/ContentApiController.java
- src/main/java/com/echall/platform/content/controller/ContentPublicController.java
- src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
- src/main/java/com/echall/platform/question/controller/QuestionApiController.java
- src/main/java/com/echall/platform/question/controller/QuestionPublicController.java
- src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
- src/main/java/com/echall/platform/scrap/domain/dto/ScrapResponseDto.java
- src/main/java/com/echall/platform/swagger/SwaggerBooleanReturn.java
- src/main/java/com/echall/platform/swagger/SwaggerReturnInterface.java
- src/main/java/com/echall/platform/swagger/SwaggerVoidReturn.java
- src/main/java/com/echall/platform/swagger/bookmark/SwaggerBookmarkCreate.java
- src/main/java/com/echall/platform/swagger/bookmark/SwaggerBookmarkList.java
- src/main/java/com/echall/platform/swagger/bookmark/SwaggerBookmarkMyList.java
- src/main/java/com/echall/platform/swagger/category/SwaggerCategory.java
- src/main/java/com/echall/platform/swagger/content/SwaggerContentCreate.java
- src/main/java/com/echall/platform/swagger/content/SwaggerContentDetail.java
- src/main/java/com/echall/platform/swagger/content/SwaggerContentPreview.java
- src/main/java/com/echall/platform/swagger/content/SwaggerContentUpdate.java
- src/main/java/com/echall/platform/swagger/question/SwaggerQuestionCreate.java
- src/main/java/com/echall/platform/swagger/question/SwaggerQuestionView.java
- src/main/java/com/echall/platform/swagger/scrap/SwaggerScrapCreate.java
- src/main/java/com/echall/platform/swagger/scrap/SwaggerScrapView.java
- src/main/java/com/echall/platform/swagger/user/SwaggerUserMyPage.java
- src/main/java/com/echall/platform/swagger/user/SwaggerUserUpdate.java
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- 스웨거 리턴 타입 실제와 일치하도록 수정
- 관련 이슈 번호: #164 
- 페이지네이션 들어간 부분은 임의의 예시라서 key가 일치하지 않음
> [REFACTORING] 스웨거 리턴 타입 일치

- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
> [REFACTORING] 스크랩 접근 권한 수정

- src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
- src/main/java/com/echall/platform/question/domain/dto/QuestionResponseDto.java
- src/main/java/com/echall/platform/question/domain/entity/QuestionDocument.java
- src/main/java/com/echall/platform/question/domain/enums/QuestionType.java
- src/main/java/com/echall/platform/question/service/QuestionServiceImpl.java
- src/main/java/com/echall/platform/script/domain/entity/CNNScript.java
- src/main/java/com/echall/platform/script/domain/entity/Script.java
- src/main/java/com/echall/platform/script/domain/entity/YoutubeScript.java
- src/main/java/com/echall/platform/swagger/user/SwaggerUserMyTime.java
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- src/main/java/com/echall/platform/user/domain/dto/UserResponseDto.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/java/com/echall/platform/util/RandomNicknameGenerator.java
- 랜덤 닉네임 수정
- 유저 가입 날짜, 수정 날짜 API 추가
- 문제 타입 추가
- 관련 이슈 번호: #173 
> [REFACTORING] 문제, 유저 리팩토링

- src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
- src/main/resources/application.yml
- src/main/resources/logback.xml
- yml 파일과 main 쪽에 한국 시간 설정 추가
- 추가적으로 로그 시간이 고정되있던 문제를 해결
- 관련 이슈 번호: #175 
- 현재 DB 시간은 UTC 입니다.
> [SETTING] 배포 서버에도 로그 한국 시간으로 찍히게 시도

- src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
> [HOTFIX] 북마크 에러 수정

- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/message/response/UserResponseCode.java
- src/main/java/com/echall/platform/message/status/UserServiceStatus.java
- src/main/java/com/echall/platform/oauth2/repository/RefreshTokenRepository.java
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- src/main/java/com/echall/platform/user/controller/UserPublicController.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- UserApiController, UserService, UserRepository 에서 기능 구현
- 로그아웃하면 AccessToken, RefreshToken 쿠키와 DB에 있는 RefreshToken을 삭제합니다.
- 저희 인증 방식에는 SecurityContextLogoutHandler().logout() 이 필요없는 것 같아서 사용하지 않았습니다.
- 관련 이슈 번호: #183 
- SecurityContextLogoutHandler().logout() 가 필요하다고 생각하시면 이유를 알려주세요! (궁금)
> [FEAT] 로그아웃 기능 개발

- src/main/java/com/echall/platform/config/SecurityConfig.java
- src/main/java/com/echall/platform/message/response/UserResponseCode.java
- src/main/java/com/echall/platform/message/status/UserServiceStatus.java
- src/main/java/com/echall/platform/user/controller/UserApiController.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- 로그인 상태 확인 API 추가
- 액세스 토큰 검증은 TokenAuthenticationFilter 에서 하고 있으므로 추가하지 않음
- 관련 이슈 번호: #185 
> [FEAT] 로그인 상태 확인 API 추가

- src/main/java/com/echall/platform/config/SecurityConfig.java
- SecurityConfig requestMatchers에서 해당 URL을 permitAll()로 설정
- 관련 이슈 번호: #186
> [REFACTOR] 컨텐츠 디테일 화면 아무나 볼 수 있게 권한 수정

- src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
> [HOTFIX] 프론트 요청에 따른 스크랩 정렬 조건 추가

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
- Azure AI 번역 API 에 JSON으로 요청할 때 특수 문자 존재할 경우 Backslash 추가
- 관련 이슈 번호: #194
> [HOTFIX] JSON 특수문자 처리

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] JSON 개행문자 처리

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] text 인코딩 조건 추가 및 os 에 따른 특수문자 처리 강화

- src/main/resources/yml/application-dev.yml
- src/main/resources/yml/application-prod.yml
> [HOTFIX] google oauth redirect-uri 추가

- src/main/java/com/echall/platform/content/controller/ContentPublicController.java
- src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
- src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
- src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
- src/main/java/com/echall/platform/content/service/ContentService.java
- src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
- src/main/java/com/echall/platform/message/error/code/ContentErrorCode.java
- src/main/java/com/echall/platform/message/status/ContentServiceStatus.java
- 검색 기능 추가
- Content Title, Prescripts 기준으로  containsIgnore, or 연산으로 가져옴
- 검색어 없을 때는 예외 처리  해 달라는 요청에 따라 NOT_FOUND 로 처리
- 관련 이슈 번호: #190
> [FEAT] 검색 기능 추가

- src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
- src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
- src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
- src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
- 북마크 전체 조회 시 리턴 타입에 컨텐츠 타입 추가
- 북마크 전체 조회 시 정렬 조건으로 최신순 추가 
- 관련 이슈 번호: #200
> [REFACTORING] 북마크 조회 조건 및 리턴 타입 추가

- src/main/java/com/echall/platform/util/RandomNicknameGenerator.java
- 무조건 index 0 만 받아서 닉네임 생성되는 이슈 해결
- 나머지 -> 곱하기 연산
- 관련 이슈 번호: #202
> [HOTFIX] 랜덤으로 닉네임 생성되게 수정

- src/main/java/com/echall/platform/content/controller/ContentApiController.java
- src/main/resources/yml/application-prod.yml
> [HOTFIX] PROD mongo 연결 수정 및 content 생성 ADMIN 권한 수정

- src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
- 게시글의 북마크 상세 조회 시 updatedAt, DESC 정렬 조건 추가
> [HOTFIX] 프론트 요청에 따른 북마크 상세조회 조건 수정

- src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
> [REFACTORING] 프론트 요청으로 로그인 성공 시 리다이렉트 uri 삭제

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] Kibana 에서 셀레니움 간편한 로그 조회를 위한 로그 메세지 수정

- src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
- src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
- src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
- src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/echall/platform/user/service/UserService.java
- src/main/java/com/echall/platform/util/CookieUtil.java
- 유튜브 북마크 상세 조회 시 시작 시간을 리턴
- 북마크 엔티티 생성 시 저장
- 프론트 쪽 연산 줄이기 위함
- Reading의 경우 0으로 저장 및 리턴
- 관련 이슈 번호: #212 
> [FEAT] 유튜브 북마크 시 시작 시간 리턴

- src/main/resources/yml/application-dev.yml
- src/main/resources/yml/application-local.yml
- src/main/resources/yml/application-prod.yml
> [HOTFIX] google oauth2 불필요한 scope 삭제

- src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
- src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
> [HOTFIX] 북마크 중복 생성 체크 잘못된 메소드명 수정

- src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
- src/main/java/com/echall/platform/user/service/UserService.java
> [HOTFIX] 유저 초기 정보 입력시 ACTIVATE 로 바뀌지 않는 로직 수정

- src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
> [HOTFIX] 스크랩 존재 확인 로직에서 유저 id 체크 안한 부분 수정

- src/main/java/com/echall/platform/oauth2/OAuth2FailureHandler.java
- OAuth2FailureHandler 에서 찍고 있는 로그 레벨을 info에서 error 추가
- OAuth2AuthenticationException 이외의 Exception에도 로그를 찍도록 수정
- 관련 이슈 번호: #221
> [BUGFIX] 소셜로그인 실패 로그 레벨 변경 및 OAuth2AuthenticationException 이외 예외 로그 추가

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] json 타입 에러로 번역 실패일 때 "" 로 채우고 로그 남기는 방식으로 수정

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] Dockerfile 과 이중 인코딩일 가능성 확인

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] 로그 확인 조건 수정

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] string() 수정 -> toString()

- src/main/java/com/echall/platform/crawling/service/TranslateService.java
> [HOTFIX] 코드 롤백

- src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
> [HOTFIX] 번역 API exception 받을 수 있게 catch 위치 수정

- src/main/java/com/echall/platform/config/SecurityConfig.java
> [HOTFIX] 프론트 요청 : url 접근 권한 제어 추가

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- deploy에서 docker run을 할 때 -v 옵션으로 logs를 매핑하고 있던 것을 삭제
- 관련 이슈 번호: #249 
- ELK에서 docker 컨테이너 로그를 받고 있기 때문에 로컬 로그는 필요없다고 판단
- 자세한 로그가 필요할 경우 docker logs를 사용할 것
> [SETTING] Docker logs 매핑 삭제

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
> [SETTING] 도커 -v 옵션 다시 추가

- user-api/src/main/java/com/biengual/userapi/UserApiApplication.java
- UserApiApplication에 타임존 설정 추가
- 관련 이슈 번호: #252
> [BUGFIX] 애플리케이션 타임존 설정 추가

- user-api/src/main/java/com/biengual/userapi/crawling/service/TranslateService.java
> [HOTFIX] translate json 타입 수정

- user-api/src/main/java/com/biengual/userapi/crawling/service/TranslateService.java
> [HOTFIX] log 롤백

- user-api/src/main/java/com/biengual/userapi/UserApiApplication.java
- entity 생성 시 BaseEntity 정보 미포함 오류 해결
> [HOTFIX] entity 생성 시 BaseEntity 정보 미포함 오류 해결

- user-api/src/main/java/com/biengual/userapi/message/status/BookmarkServiceStatus.java
- BOOKMARK_ALREADY_EXISTS : U-B-903 -> U-B-902
> [REFACTORING] 삭제된 실패 메세지에 따라 BOOKMARK_ALREADY_EXISTS code 수정

- user-api/src/main/java/com/biengual/userapi/content/controller/ContentApiController.java
- user-api/src/main/java/com/biengual/userapi/user/controller/UserApiController.java
- 모든 `@PatchMapping`을 `@PutMapping`으로 수정
- 관련 이슈 번호: #269 
- merge 된 후 프론트 분들에게 공유 드리겠습니다.
> [REFACTOR] 모든 `@PatchMapping`을 `@PutMapping`으로 수정

- user-api/src/main/java/com/biengual/userapi/oauth2/OAuth2SuccessHandler.java
- user-api/src/main/java/com/biengual/userapi/user/domain/UserEntity.java
- user-api/src/main/java/com/biengual/userapi/util/CookieUtil.java
- 첫 로그인 시 리다이렉트 URL 주소 변경
- 첫 로그인 시 리다이렉트 URL에 returnUrl 쿠키 여부에 따른 returnUrl 쿼리 파라미터 추가
- 첫 로그인한 후 본인 정보 수정을 하면 유저 상태를 active로 변경
- 기존에 사용하던 returnUrl 쿠키 key 값을 return_url에서 returnUrl로 변경
- 관련 이슈 번호: #265
> [REFACTOR] 첫로그인 시 리다이렉트 URL 변경

- user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
- user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
- user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentAdminView.java
- user-api/src/main/java/com/biengual/userapi/user/domain/UserCategoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/user/domain/UserCategoryRepository.java
- user-api/src/main/java/com/biengual/userapi/user/domain/UserCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/user/domain/UserRepository.java
- user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
- user-api/src/main/resources/db/migration/V1.2.0__alter.sql
- user-api/src/test/java/com/biengual/userapi/service/UserServiceTest.java
- 어드민이 컨텐츠 관리 목적의 컨텐츠 조회
- DEACTIVATED 도 조회 가능
- Content 엔티티에 num_of_quiz col 추가 및 관련 업데이트 용 flyway sql 추가
- 관련 이슈 번호: #273
> [REFACTOR] Admin 페이지 컨텐츠 상태 무관하게 조회

- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
-  mapper에서 +- 1을 하도록 수정
- 관련 이슈 번호: #299
> [REFACTOR] 페이지 넘버 1부터 시작하게끔 수정

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java
- user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionStoreImpl.java
- question 생성 시 num_of_quiz 업데이트 로직 추가
- 관련 이슈 번호: #273 
> [FEAT] question 생성 시 num_of_quiz 업데이트 로직 추가

- user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepository.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- userId에 대해서만 찾던 것을 contentId에 대해서도 북마크 레포지토리에서 찾도록 수정
- 관련 이슈 번호: #312
> [BUGFIX] 유저의 전체 컨텐츠에 대한 북마크를 찾고 있던 것을 해당 컨텐츠의 유저 북마크로 수정

- user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkInfo.java
- user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkApiController.java
- user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkResponseDto.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapInfo.java
- user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapResponseDto.java
- Dto, Info, Respository 변경
- 관련 이슈 번호: #295 
- TODO 확인해주세요.
> [REFACTOR] 프론트 요청에 따른 나의 스크랩 조회, 나의 북마크 전체 조회 리팩토링

- user-api/src/main/resources/static/robots.txt
- - /.env 만 허용 안하게 했고, 웹 크롤러로 인한 로그인지 확인하기 위한 작업
- 관련 이슈 번호: #316
> [BUGFIX] robots.txt 추가

- user-api/src/main/resources/static/robots.txt
- 웹 크롤러로 인한 문제인지, 정확하게 파악하기 위해 모든 경로 허용 x
- 관련 이슈 번호: #317
> [BUGFIX] robots.txt 다 허용 못하게 설정

- user-api/build.gradle
- bootJar 시 중복 항목 처리 전략 추가
- EXCLUDE: 중복 항목 중 하나를 제외하고 나머지를 포함합니다. 즉, 중복된 항목은 빌드 결과물에서 무시됩니다.
- 관련 이슈 번호: #324
> [FIX] bootJar 설정 추가

- .github/workflows/dev-deploy.yml
- 모델 로드에 필요한 txt 파일 160 MB -> 100 MB 경량화
- 관련 이슈 번호: #289
> [Feat] Word2Vec 모델 경량화 1차

- .gitignore
- user-api/src/main/java/com/biengual/userapi/nlp/NLPAnalyzer.java
- 경량화를 위해 모델 로드에 사용하는 txt 파일 크기를 줄임
- 현재 734 MB
- 관련 이슈 번호: #289 
- dev 서버에 먼저 배포를 한 후, 잘 돌아간다면 prod 서버에도 사용할 수 있게 서버 작업을 할 예정
> [FEAT] Word2Vec 모델 경량화 2차

- .github/workflows/prod-deploy.yml
- 스왑 메모리 4G로 증설
- word2vec.txt 추가
- prod 배포 워크플로우 docker 매핑 추가
- 관련 이슈 번호: #328
> [SETTING] NLP 사용을 위한 운영 서버 작업

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
- user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapApiController.java
- Dto 및 Info에 Boolean isScrapped 멤버 변수 추가
- 기존 사용하던 Reader 메서드에 로직 추가
- 관련 이슈 번호: #331 
- 비로그인 시 isScrapped는 false
> [REFACTOR] 컨텐츠 디테일 조회 시 응답에 isScrapped 추가

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
- user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryCustomRepository.java
- Dto, Info 에 멤버변수 learningRate 추가
- mapper, reader 수정
- 관련 이슈 번호: #340 
- 클린 코드화 필요!
> [REFACTOR] 컨텐츠 디테일 조회에 learningRate 추가

- biengual-core/src/main/java/com/biengual/core/annotation/Manager.java
- biengual-core/src/main/java/com/biengual/core/annotation/Validator.java
- biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
- biengual-core/src/main/java/com/biengual/core/domain/entity/pointdatamart/PointDataMart.java
- biengual-core/src/main/java/com/biengual/core/domain/entity/usercontenthistory/PaymentContentHistoryEntity.java
- biengual-core/src/main/java/com/biengual/core/enums/PointReason.java
- user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
- user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
- user-api/src/main/java/com/biengual/userapi/mission/application/MissionServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentReader.java
- user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentRepository.java
- user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentStore.java
- user-api/src/main/java/com/biengual/userapi/payment/infrastructure/PaymentReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/payment/infrastructure/PaymentStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/point/domain/PointManager.java
- user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java
- user-api/src/main/java/com/biengual/userapi/user/application/UserServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/user/domain/UserService.java
- user-api/src/main/java/com/biengual/userapi/validator/PointValidator.java
- user-api/src/main/resources/db/migration/V1.6.0__alter.sql
- user-api/src/main/resources/db/migration/V1.7.0__create.sql
- [[FEAT] point reason 에 퀴즈 정답인 경우 추가](https://github.com/Kernel360/F2-BIENGUAL-BE/commit/1ec971245e4b0d870419f1b7a28e20352e7d8480)
- [[REFACTOR] PointValidator 와 PointManager를 이용하여 point 변경 검증 및 관리](https://github.com/Kernel360/F2-BIENGUAL-BE/commit/27ab48166967c2af8cac9294cce0db43b812ea9e)
- point 검증 및 관리 기능 분리
- [[FEAT] 일일 미션에 따른 포인트 업데이트](https://github.com/Kernel360/F2-BIENGUAL-BE/commit/c3bb7a383a2692092517bb3a3cd7df5b208c40f6)
- 일일 미션 성공 시 포인트 업데이트
- [[FEAT] 유료 컨텐츠 기록 저장](https://github.com/Kernel360/F2-BIENGUAL-BE/commit/d36a8abbb4fe8712caf59edb72a70ee32f63ccf4)
- 유료 컨텐츠 포인트 중복 사용 방지를 위한 기록 저장
- 관련 이슈 번호: #310 
- 310의 동시성 확인은 다음 PR에서 진행 예정
- 퀴즈 관련 사항은 추후 퀴즈 로직 수정 시에 진행 예정
- ***만료된 PaymentContentHistoryEntity는 삭제할 필요가 있을까요? 삭제 가능하게 expiredAt을 넣어두긴 했습니다***
> [FEAT] 포인트 사용 내역 저장 기능 추가

- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetRecentLearning.java
- user-api/src/main/java/com/biengual/userapi/learning/presentation/LearningPublicController.java
- user-api/src/main/java/com/biengual/userapi/learning/presentation/swagger/SwaggerUpdateLearningRate.java
- 잘못된 Swagger Example Value 수정
- 추가적으로 Dashboard Dto 위치 변경
- 관련 이슈 번호: #347
> [FIX] 잘못된 Swagger Example Value 수정

- biengual-core/src/main/java/com/biengual/core/response/status/MissionHistoryServiceStatus.java
- biengual-core/src/main/java/com/biengual/core/response/success/MissionHistorySuccessCode.java
- user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/application/MissionHistoryServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryInfo.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryReader.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryService.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/infrastructure/MissionHistoryReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryPublicController.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/RecentHistoryDto.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/swagger/SwaggerMissionHistoryRecent.java
- 최근 미션 기록 몇 개 성공했는지에 대한 정보 리턴
- 메인 페이지에서 로그인한 유저에 대해 최근 미션 성공 갯수 보여주는데 사용할 API
- 관련 이슈 번호: #310 
- 달력 쪽에 보여줄 미션 기록은 대시보드 작업 때 진행 예정
> [FEAT] 최근 미션 기록 조회 기능 추가

- biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryPublicController.java
- content 의 createdAt을 view 에서는 확인하지 않아서 모두 포인트가 필요하다고 리턴되고 있어서 이에 대한 쿼리 수정
- 기존 논의했던 대로 7일로 수정
> [HOTFIX] 5일 -> 7일 수정 및 컨텐츠 조회 시 컨텐츠 생성 날짜 확인하는 로직 빠진 부분 추가

- user-api/src/main/java/com/biengual/userapi/mission/application/MissionServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/validator/PointValidator.java
- 기존 미션 완료에 따른 포인트 업데이트 검증 로직이 잘못 되어 있어서 수정함
> [HOTFIX] 미션 포인트 중복 업데이트 로직 해결

- biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
- user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
- user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryCustomRepository.java
- user-api/src/main/resources/db/migration/V1.8.0__alter.sql
- ContentEntity 변경 및 Flyway 버전 추가
- Dto, Info, Mapper 수정
- ContentCustomRepository 수정
- 관련 이슈 번호: #357 
- dev와 prod의 기존 데이터 정합성은 배포된 후 로컬에서 진행할 예정입니다.
> [REFACTOR] 컨텐츠를 보여주는 API 들의 응답에 영상 길이를 포함하여 보내도록 수정

- biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocumentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/question/application/QuestionServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/question/domain/QuestionStore.java
- user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionApiController.java
- 기존 문제 삭제를 위해 만들었던 임시 API 삭제
- 메인 DB에서도 기존 문제 삭제하고 나면 이 PR도 main으로 머지할 예정입니다
> [HOTFIX] 기존 문제 삭제용 API 삭제

- biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
- biengual-core/src/main/java/com/biengual/core/domain/entity/learning/RecentLearningHistoryEntity.java
- biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
- biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
- biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
- user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
- user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetCategoryLearningDto.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetCategoryLearning.java
- user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/learning/domain/CategoryLearningHistoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/learning/domain/LearningHistoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/validator/LearningValidator.java
- Layerd Architecture 컨벤션에 맞게 구현
- 학습 내역 관련 로직 수정
- 관련 이슈 번호: #359
> [Feat] 월별 카테고리별 학습량 조회 기능 개발

- biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
- biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
- user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
- user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningSummaryDto.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetRecentLearningSummary.java
- user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
- Layerd Architecture 컨벤션에 맞게 구현
- 관련 이슈 번호: #365
> [FEAT] 대시보드 첫화면에서 사용하는 최근 학습 컨텐츠 1개를 요약하여 보여주는 API 기능 개발

- user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryPublicController.java
- 최근 미션 기록 리턴 값 최대 5일로 고정
- 관련 이슈 번호: #367
> [REFACTOR] 최근 미션 기록 리턴 값 최대 5일로 고정

- user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
> [HOTFIX] 문제 조회 시 맞춘 문제 검증 로직 오류 수정

- biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
- user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
- user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
- user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
- user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetQuestionSummaryDto.java
- user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryCustomRepository.java
- 리턴 값 수정
- 확률 -> 개수
- 분자/분모 형태의 확률 에서 분자, 분모 형태로 개수로 각각 보냄(막대기형 그래프로 표시할 예정)
- 각 주차 별로 데이터 조회하도록 수정(월별 -> 주별)
- 입력 날짜 기준 5주차(입력 날짜 없으면 오늘이 기준)
- 매주 시작 기준은 **월요일**
- 관련 이슈 번호: #391
> [REFACTOR] 대시보드 퀴즈 조회 내용 수정

- user-api/src/main/resources/yml/application-dev.yml
- user-api/src/main/resources/yml/application-local.yml
- user-api/src/main/resources/yml/application-prod.yml
- user-api/src/test/resources/application-test.yml
-  yml 파일 127.0.0.1로 되어있는 부분을 localhost로 변경
- env 파일도 마찬가지로 수정
- 관련 이슈 번호: #395
- env 깃허브 시크릿키에 반영하겠습니다.
- 되는지는 확인해야합니다.
> [BUGFIX] yml 파일 127.0.0.1 을 localhost로 변경

- user-api/src/main/resources/yml/application-dev.yml
- user-api/src/main/resources/yml/application-prod.yml
- yml 파일 Redis host를 환경변수로 실제 인스턴스 서버 IP로 받게끔 변경
- 관련 이슈 번호: #395
> [FIX] yml 파일 Redis host를 환경변수로 실제 인스턴스 서버 IP로 받게끔 변경

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
> [HOTFIX] 이전 response 수정 pr 에서 수정되지 않았던 constructor 수정

- user-api/src/main/java/com/biengual/userapi/oauth2/info/KakaoUserInfo.java
- user-api/src/main/java/com/biengual/userapi/oauth2/info/NaverUserInfo.java
- 카카오 로그인 시 받는 nickname 을 user 엔티티의 username으로 받도록 수정
- 관련 이슈 번호: #414
> [REFACTOR] 카카오 로그인 시 받는 nickname 을 user 엔티티의 username으로 받도록 수정

- biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
- user-api/src/main/resources/db/migration/V1.16.0__update.sql
- 프론트 요청 : 카테고리 매핑 변경, Unknown -> ETC
> [HOTFIX] 프론트 요청 : 카테고리 매핑 변경, Unknown -> ETC

- user-api/src/main/java/com/biengual/userapi/category/application/CategoryServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/category/domain/CategoryReader.java
- user-api/src/main/java/com/biengual/userapi/category/domain/CategoryService.java
- user-api/src/main/java/com/biengual/userapi/category/infrastructure/CategoryReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/category/presentation/CategoryPublicController.java
- 컨텐츠 타입에 따른 카테고리 조회
- 각 카테고리에 컨텐츠 타입 별로 없는 데이터가 존재하여 학습 페이지에서 존재하는 카테고리만 가져오도록 API 추가
- 관련 이슈 번호: #419
> [FEAT] 컨텐츠 타입에 따른 카테고리 조회

- user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningReaderImpl.java
- user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
- 첫 로그인 시 카테고리 추천에서 랜덤으로 주기 위한 로직
- 카테고리 선정, 컨텐츠 한 개라도 학습하면 필요 없기 때문에 랜덤으로 넣음
> [HOTFIX] 첫 로그인 시 카테고리 추천에서 랜덤으로 주기 위한 로직

- biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
- biengual-core/src/main/java/com/biengual/core/util/GlobalExceptionLogSchema.java
- biengual-core/src/main/java/com/biengual/core/util/RestControllerSuccessLogSchema.java
- user-api/src/main/java/com/biengual/userapi/aop/LoggingAspect.java
- user-api/src/main/java/com/biengual/userapi/config/HttpRequestFilterConfig.java
- user-api/src/main/java/com/biengual/userapi/config/ScheduleConfig.java
- user-api/src/main/java/com/biengual/userapi/filter/ReadableRequestWrapper.java
- user-api/src/main/java/com/biengual/userapi/filter/ReadableRequestWrapperFilter.java
- user-api/src/main/resources/logback.xml
- 현재는 RestController와 GlobalExceptionHandler에 대한 로그를 고도화 하였습니다.
- requestBody를 얻기위해 필터를 통해 캐싱합니다.
**RestController 성공 시**
**global exeption 발생 시**
**global exeption 발생 시 - 잡지 않은 Exception**
- 관련 이슈 번호: #412 
- 코드만 변경한 상태이고 이후, ELK 작업을 해야합니다.
- 잡지 않은 Exception 같은 경우에는 server와 thread를 이용하면 진짜 예외 메시지를 볼 수 있습니다.
> [REFACTOR] 로깅 고도화 1차

- user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
- 셔플 전에 3개 선택 후 셔플은 랜덤 선택이 아님
- 전체 선택 후 셔플 이후 3개만 선택
> [HOTFIX] 의미없는 셔플 수정

- user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
> [HOTFIX] 북마크 추천 시스템 중복 업데이트 방지

- user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
> [HOTFIX] 컨텐츠 타입 별 카테고리 권한

- biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
- GlobalExceptionHandler의 handleOtherException 에 에러 메시지 로깅 추가
- 관련 이슈 번호: #434
> [BUGFIX] 핸들링하지 않는 모든 예외처리에서 진짜 에러메시지도 최소 한번은 찍도록 수정

- biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
- user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
2024-11-22 11:57
#435 PR 까지 머지
> DEV Into MAIN

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- 포인트 지불했으나 isPointRequired 가 true 로 리턴되던 이슈 해결
- 컨텐츠 만료 확인 로직 불필요
- 이 로직이 다른 로직과 상관없이 isPointRequired를 결정짓고 있었음
- 근데 왜 그동안 잘 동작 했는지는 확인을 다시 해봐야 함
> [HOTFIX] 포인트 지불했으나 isPointRequired 가 true 로 리턴되던 이슈 해결

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderInfo.java
- user-api/src/main/java/com/biengual/userapi/recommender/presentation/GetPreviewDto.java
- Dto, Info 및 Repository 변경
- 관련 이슈 번호: #446
> [REFACTOR] 프론트 요청에 따른 카테고리 기반 추천 콘텐츠 응답에 calculatedLevel 추가

- user-api/Dockerfile
- user-api/Dockerfile_Selenium
- 기존 셀레니움 관련 Layer를 Dockerfile_Selenium 파일로 옮겨서 빌드 시간 개선 시도
- 관련 이슈 번호: #454 
- dev에 머지가 되면 컨텐츠 생성이 정상적으로 되는지 확인해봐야 합니다.
> [REFACTOR] 스프링부트 이미지를 빌드할 때, 셀리니움 세팅 부분을 미리 만들어진 이미지에서 가져오도록 수정

- user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
> [HOTFIX] OpenSearch DEV 연결 테스트

- user-api/src/main/resources/yml/application-dev.yml
- 시크릿키에 반영되어 있는 변수명에 맞게 수정
- 관련 이슈 번호:
> [BUGFIX]: #464 PR 에서 변경된 OpenSearch Port 명을 수정

- user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
- user-api/src/main/resources/yml/application-dev.yml
- user-api/src/main/resources/yml/application-local.yml
> [HOTFIX] OpenSearch 연결 문제 해결 - 포트 이슈

- biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
- user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentSearchRepositoryImpl.java
- user-api/src/main/resources/yml/application-dev.yml
- user-api/src/main/resources/yml/application-local.yml
- user-api/src/main/resources/yml/application-prod.yml
- OpenSearch Prod 세팅
- .env 파일 수정되었습니다
> [HOTFIX] PROD OpenSearch index 추가

- user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
> [HOTFIX] s3Url 적용 안된 곳 수정

- user-api/src/main/java/com/biengual/userapi/crawling/application/JsoupWebCrawler.java
- imgUrl null 로 기본값 설정 후 이미지 확인하면서 최대값 찾도록 수정
- 관련 이슈 번호: #474 
- 이미지가 존재하는지에 대한 검증은 바로 위쪽에서 하고 있음
```
// 이미지 URL 추출
Elements images = doc.select("img.image__dam-img[src]");
if (images.isEmpty()) {
throw new CommonException(CRAWLING_JSOUP_FAILURE);
}
```
> [REFACTOR] imgUrl null 로 기본값 설정 후 이미지 확인하면서 최대값 찾도록 수정

- user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
- user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
> [REFACTOR] 문제 생성 자동화

- user-api/src/main/java/com/biengual/userapi/filter/ServerTimingFilter.java
- responseWrapper에서 받아온 response body를 response에 copy
- 관련 이슈 번호: #490 
- 요청에 대한 응답은 HttpServletResponse 객체인 reponse를 보여줍니다.
- 그래서 responseWrapper가 실제 응답 Body를 갖고있기 때문에 response에 복사를 해줘야 response에 실제 응답 Body가 담기게 해야합니다.
> [BUGFIX] Response Body가 사라진 문제 해결

- biengual-core/src/main/java/com/biengual/core/response/error/code/ImageErrorCode.java
- biengual-core/src/main/java/com/biengual/core/response/status/ImageServiceStatus.java
- user-api/src/main/java/com/biengual/userapi/image/infrastructure/ImageStoreImpl.java
- user-api/src/main/resources/yml/application-prod.yml
- S3 배포 서버 설정 및 이미지 커스텀 예외 수정
- 관련 이슈 번호: #465 
- 12/13 (금) 에 확인하고 main 머지 예정
- OpenSearch Security 도 이 때 적용 예정
> [REFACTOR] S3 배포 서버 설정 및 이미지 커스텀 예외 수정

- user-api/src/main/java/com/biengual/userapi/config/S3Config.java
[HOTFIX] S3Config 빠진 PROD Profile 설정 추가
> [HOTFIX] S3Config 빠진 PROD Profile 설정 추가

- user-api/src/main/resources/yml/application-dev.yml
- user-api/src/main/resources/yml/application-prod.yml
> [HOTFIX] .yml CDN 분리

- biengual-core/src/main/java/com/biengual/core/constant/CrawlingAutomationConstant.java
- biengual-core/src/main/java/com/biengual/core/response/error/code/CrawlingErrorCode.java
- user-api/src/main/java/com/biengual/userapi/validator/CrawlingValidator.java
> [HOTFIX] 유튜브 크롤링 시 쇼츠 제외

- user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
- [HOTFIX] 카테고리 조회 시 모두 DEACTIVATED 이면 카테고리 조회 안 되도록 수정
> [HOTFIX] 카테고리 조회 시 모두 DEACTIVATED 이면 카테고리 조회 안 되도록 수정

- user-api/src/main/java/com/biengual/userapi/recommender/application/ContentRecommender.java
… 여유 메모리 할당
- [HOTFIX] 카테고리 추천 시스템 - Index Out Of Bounds 해결을 위해 array initialize 에서 여유 메모리 할당
> [HOTFIX] 카테고리 추천 시스템 - Index Out Of Bounds 해결

- user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/recommender/application/ContentRecommender.java
[HOTFIX] 카테고리 추천 시스템 - Index Out Of Bounds 해결을 위해 array initialize 에서 여유 메모리 할당
> DEV to MAIN 1212 HOTFIX

- biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
- user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
> [HOTFIX] 검색어 20자 제한

- biengual-core/src/main/java/com/biengual/core/domain/entity/recommender/BookmarkRecommenderEntity.java
- user-api/src/main/resources/db/migration/V1.23.0__alter.sql
- Mongo DB 에서 가져온 스크립트여서 varchar(255)로는 저장할 수 없는 이슈 발생
- `en_detail`, `ko_detail` 을 varchar(255) 에서 TEXT 로 크기 변경
> [HOTFIX] BookmarkRecommenderEntity en_detail, ko_detail 크기 변경

- biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
- BookmarkRecommenderEntity end_of_week 날짜 withNano 가 반올림 시키던 이슈 해결
> [HOTFIX] BookmarkRecommenderEntity end_of_week 날짜

- biengual-core/src/main/java/com/biengual/core/enums/PointReason.java
> [REFACTOR] 미션 포인트 최종 확정

- biengual-core/src/main/java/com/biengual/core/domain/entity/recommender/BookmarkRecommenderEntity.java
- user-api/src/main/resources/db/migration/V1.24.0__alter.sql
- BookmarkRecommenderEntity *_detail 사이즈 LONGTEXT 로 수정
> [REFACTOR] BookmarkRecommenderEntity *_detail 사이즈 LONGTEXT 로 수정

- user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
- user-api/src/main/java/com/biengual/userapi/content/domain/ContentSearchRepositoryImpl.java
> [HOTFIX] opensearch 노드 과부하 방지 설정 수정

- user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
> [HOTFIX] 더 이상 자동 크롤링 되지 않도록 수정

- user-api/src/main/java/com/biengual/userapi/recommender/application/RecommenderServiceImpl.java
- user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
- user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderReader.java
- user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderReaderImpl.java
- 주간 북마크 추천 데이터 없는 경우 12/20일 기준 주간으로 데이터 선정
- 관련 이슈 번호: #529
> [REFACTOR] 북마크 추천 데이터 없을 경우 기존 데이터 활용

- user-api/build.gradle
- user-api/src/main/java/com/biengual/userapi/config/StanfordCoreNLPConfig.java
- user-api/src/main/java/com/biengual/userapi/config/Word2VecConfig.java
- user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
- user-api/src/main/java/com/biengual/userapi/nlp/CategoryClassifier.java
- user-api/src/main/java/com/biengual/userapi/nlp/NLPAnalyzer.java
> [HOTFIX] Weight Reduction : stop to use NLP model
